api_v1:
    prefix: /api/v1
    resource: '../src/Controller/Api/V1'
    defaults: { _format: json }
    requirements:
        format: json

api_login_check:
    path: /api/v1/login
    methods:  [POST]

gesdinet_jwt_refresh_token:
    path:       /api/v1/token/refresh
    controller: gesdinet.jwtrefreshtoken::refresh
